# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9692a0342aa45ee233cfb94f87c5d2fbe47c4f64aa38eb5d3b0fa5acca0004a67f52a5a525887135d2cb998e87ef6324b7892fb7de05e7000cf28b4039af8c3a

test:
  secret_key_base: 8f82d43ccb4240668eedd4415ec6c9b41261c02d87c59bab3ca3d1ad11507af55b043a5705f2d4fd367229224c9a829fdf874851fa9ee74cf28f9e6c737f7bd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
